### ISSUE TITLE
A labelled gauge with a pointer-needle shall shall be visible upon entering the app

### ISSUE THREAD

**Issue by franzmoro** [franzmoro/en-gauge-o-meter#4]
Similar as the below image.
![](https://cloud.githubusercontent.com/assets/122096/18757750/2bc9c6a2-80ed-11e6-94dc-40e37d802be2.jpg)

## Tasks / Sequence
- [x] hard-coded version in Canvas
- [x] props from Redux store
- [x] numbers from API, backup with default props / initial Redux store
